import type { Jurisdiction } from "./types";

export const CONTINENTS: Record<string, string[]> = {
  Americas: ["BR", "BR_INTL", "US", "CA", "AR", "MX", "CL", "CO"],
  Europe: ["GB", "DE", "FR", "PT", "ES", "NL", "IT", "CH", "SE", "NO", "PL"],
  "Asia-Pac": ["AU", "JP", "SG", "HK", "NZ", "IN"],
};

export const J: Record<string, Jurisdiction> = {
  BR: {
    name: "Brasil — Doméstico",
    flag: "BR",
    cur: "BRL",
    sym: "R$",
    sc: "BR",
    taxMode: "monthly_dt",
    rate: 0.2,
    swingRate: 0.15,
    swingExemption: 20000,
    code: "DARF 6015",
    note: "Day Trade: 20% IR mensal (DARF 6015). Swing/Position: 15% — isento se vendas ≤ R$20.000/mês. Prejuízo carrega indefinidamente, mesmo tipo.",
    ass: ["WINFUT", "WDOFUT", "DOLFUT", "BITFUT", "GLD FUT", "ETH FUT", "SOL FUT", "Acoes", "Opcoes", "FII", "BDR", "Outro"],
  },
  BR_INTL: {
    name: "Brasil — Forex Internacional",
    flag: "BR",
    cur: "USD",
    sym: "$",
    sc: "BR_INTL",
    taxMode: "annual",
    rate: 0.15,
    code: "DIRPF + Carnê-Leão",
    note: "Operações com corretoras internacionais: 15% anual sobre ganhos de capital no exterior (Lei 14.754/2023). Carnê-Leão mensal se ganhos > R$2.259,20/mês. Conversão pelo PTAX. DIRPF: 31/maio.",
    ass: ["Forex", "CFD", "Crypto", "Stocks", "ETF", "Futures", "Other"],
  },
  US: {
    name: "United States",
    flag: "US",
    cur: "USD",
    sym: "$",
    sc: "INTL",
    taxMode: "quarterly_annual",
    rate: null,
    code: "Form 1040 + Schedule D",
    note: "Short-term gains (< 1 year): ordinary income 10–37%. Quarterly estimated taxes: Apr 15, Jun 15, Sep 15, Jan 15. Wash sale: no loss deduction if same security bought within 30 days.",
    ass: ["Stocks", "ETF", "Options", "Futures", "Forex", "Crypto", "Other"],
    brackets: [
      { max: 11600, rate: 0.1 },
      { max: 47150, rate: 0.12 },
      { max: 100525, rate: 0.22 },
      { max: 191950, rate: 0.24 },
      { max: 243725, rate: 0.32 },
      { max: 609350, rate: 0.35 },
      { max: 999999999, rate: 0.37 },
    ],
    qDates: ["Apr 15", "Jun 15", "Sep 15", "Jan 15"],
  },
  GB: {
    name: "United Kingdom",
    flag: "GB",
    cur: "GBP",
    sym: "£",
    sc: "INTL",
    taxMode: "annual",
    rate: null,
    code: "Self Assessment",
    note: "CGT: 18% basic / 24% higher. Annual exempt: GBP 3,000. Spread betting: tax-free. CFDs: taxable CGT. Tax year: Apr 6 – Apr 5. SA deadline: Jan 31.",
    ass: ["Stocks", "CFD", "Spread Bet", "Forex", "Options", "ETF", "Other"],
  },
  AU: {
    name: "Australia",
    flag: "AU",
    cur: "AUD",
    sym: "A$",
    sc: "INTL",
    taxMode: "annual",
    rate: null,
    code: "ATO — ITR",
    note: "Day trading = business income (marginal rate, no CGT discount). Holdings > 12 months: 50% CGT discount. Tax year: Jul 1 – Jun 30. ITR deadline: Oct 31.",
    ass: ["Stocks", "ETF", "Futures", "Forex", "CFD", "Crypto", "Other"],
  },
  CA: {
    name: "Canada",
    flag: "CA",
    cur: "CAD",
    sym: "C$",
    sc: "INTL",
    taxMode: "annual",
    rate: null,
    code: "T1 General",
    note: "50% of capital gains included in taxable income. Active traders: 100% as business income. T1 deadline: Apr 30.",
    ass: ["Stocks", "ETF", "Options", "Futures", "Forex", "Crypto", "Other"],
  },
  DE: {
    name: "Germany",
    flag: "DE",
    cur: "EUR",
    sym: "€",
    sc: "INTL",
    taxMode: "annual",
    rate: 0.25,
    code: "Anlage KAP",
    note: "Abgeltungsteuer: 25% + 5.5% Soli (26.375% effective). Annual exemption: EUR 1,000. Withheld by German brokers.",
    ass: ["Stocks", "ETF", "Options", "Futures", "Forex", "CFD", "Crypto", "Other"],
  },
  FR: {
    name: "France",
    flag: "FR",
    cur: "EUR",
    sym: "€",
    sc: "INTL",
    taxMode: "annual",
    rate: 0.3,
    code: "Formulaire 2086",
    note: "PFU: 30% flat (12.8% income + 17.2% social charges). Crypto: also 30%. Deadline: May–June.",
    ass: ["Stocks", "ETF", "Options", "Futures", "Forex", "CFD", "Crypto", "Other"],
  },
  PT: {
    name: "Portugal",
    flag: "PT",
    cur: "EUR",
    sym: "€",
    sc: "INTL",
    taxMode: "annual",
    rate: 0.28,
    code: "Modelo 3 — Anexo G",
    note: "IRS tributação autónoma: 28% sobre mais-valias. Crypto: 28% (≥1 year: exempt). Modelo 3 deadline: Jun 30.",
    ass: ["Acoes", "ETF", "Opcoes", "Futuros", "Forex", "CFD", "Criptomoedas", "Outro"],
  },
  ES: {
    name: "Spain",
    flag: "ES",
    cur: "EUR",
    sym: "€",
    sc: "INTL",
    taxMode: "annual",
    rate: null,
    code: "Modelo 100",
    note: "Ganancias patrimoniales: 19% (≤ €6k), 21% (6–50k), 23% (50–200k), 27% (200k–300k), 28% (>300k). Deadline: Jun 30.",
    ass: ["Acciones", "ETF", "Opciones", "Futuros", "Forex", "CFD", "Cripto", "Otro"],
  },
  NL: {
    name: "Netherlands",
    flag: "NL",
    cur: "EUR",
    sym: "€",
    sc: "INTL",
    taxMode: "annual",
    rate: null,
    code: "Aangifte IB",
    note: "Box 3: fictional return tax on net wealth (not realized gains). Rate 36% on assumed return. IB deadline: May 1.",
    ass: ["Stocks", "ETF", "Options", "Futures", "Forex", "Crypto", "Other"],
  },
  IT: {
    name: "Italy",
    flag: "IT",
    cur: "EUR",
    sym: "€",
    sc: "INTL",
    taxMode: "annual",
    rate: 0.26,
    code: "Modello 730 / Unico",
    note: "Imposta sostitutiva: 26% su redditi di natura finanziaria. Deadline: Sep 30 (Unico) or Apr 30 (730).",
    ass: ["Azioni", "ETF", "Opzioni", "Futures", "Forex", "CFD", "Crypto", "Altro"],
  },
  CH: {
    name: "Switzerland",
    flag: "CH",
    cur: "CHF",
    sym: "CHF",
    sc: "INTL",
    taxMode: "annual",
    rate: null,
    code: "Steuererklärung",
    note: "Private investors: no CGT. Professional traders: income tax. Wealth tax 0.1–0.9% by canton.",
    ass: ["Stocks", "ETF", "Options", "Futures", "Forex", "CFD", "Crypto", "Other"],
  },
  SE: {
    name: "Sweden",
    flag: "SE",
    cur: "SEK",
    sym: "kr",
    sc: "INTL",
    taxMode: "annual",
    rate: 0.3,
    code: "Inkomstdeklaration 1",
    note: "Kapitalskatt: 30% on capital gains. ISK account: flat annual 0.888% on value. Deadline: May 2.",
    ass: ["Stocks", "ETF", "Options", "Futures", "Forex", "Crypto", "Other"],
  },
  NO: {
    name: "Norway",
    flag: "NO",
    cur: "NOK",
    sym: "kr",
    sc: "INTL",
    taxMode: "annual",
    rate: null,
    code: "Skattemeldingen",
    note: "Kapitalgevinstskatt: 37.84% (22% × 1.72 multiplier for shares via aksjesparekonto). Deadline: Apr 30.",
    ass: ["Stocks", "ETF", "Options", "Futures", "Forex", "Crypto", "Other"],
  },
  PL: {
    name: "Poland",
    flag: "PL",
    cur: "PLN",
    sym: "zl",
    sc: "INTL",
    taxMode: "annual",
    rate: 0.19,
    code: "PIT-38",
    note: "Podatek od zysków kapitałowych: 19% flat. PIT-38 deadline: Apr 30.",
    ass: ["Stocks", "ETF", "Options", "Futures", "Forex", "CFD", "Crypto", "Other"],
  },
  JP: {
    name: "Japan",
    flag: "JP",
    cur: "JPY",
    sym: "¥",
    sc: "INTL",
    taxMode: "annual",
    rate: 0.20315,
    code: "Kakutei Shinkoku",
    note: "Bunri Kazei: 20.315% (15% national + 5% local + 0.315%). Special accounts withhold tax. Deadline: Mar 15.",
    ass: ["Stocks", "ETF", "Options", "Futures", "Forex", "CFD", "Crypto", "Other"],
  },
  SG: {
    name: "Singapore",
    flag: "SG",
    cur: "SGD",
    sym: "S$",
    sc: "INTL",
    taxMode: "annual",
    rate: 0,
    code: "IRAS Form B",
    note: "No capital gains tax. Frequent traders may be assessed as business income. ITR deadline: Apr 15.",
    ass: ["Stocks", "ETF", "Options", "Futures", "Forex", "CFD", "Crypto", "Other"],
  },
  HK: {
    name: "Hong Kong",
    flag: "HK",
    cur: "HKD",
    sym: "HK$",
    sc: "INTL",
    taxMode: "annual",
    rate: 0,
    code: "BIR51",
    note: "No capital gains tax. Professional traders: profits tax 16.5%. BIR51 deadline: Apr 1.",
    ass: ["Stocks", "ETF", "Options", "Futures", "Forex", "Crypto", "Other"],
  },
  IN: {
    name: "India",
    flag: "IN",
    cur: "INR",
    sym: "₹",
    sc: "INTL",
    taxMode: "annual",
    rate: null,
    code: "ITR-3",
    note: "STCG (< 1yr, STT paid): 20%. LTCG > INR 1L: 12.5%. Intraday = speculative business income. ITR-3 deadline: Jul 31.",
    ass: ["Stocks", "F&O", "Commodities", "Forex", "ETF", "Crypto", "Other"],
  },
  AR: {
    name: "Argentina",
    flag: "AR",
    cur: "ARS",
    sym: "$",
    sc: "INTL",
    taxMode: "annual",
    rate: null,
    code: "F.2280",
    note: "Renta financiera cedular: 15% (exterior) / 5% (pesos).",
    ass: ["Acciones", "CEDEARs", "Futuros", "Forex", "Cripto", "Otro"],
  },
  MX: {
    name: "Mexico",
    flag: "MX",
    cur: "MXN",
    sym: "$",
    sc: "INTL",
    taxMode: "annual",
    rate: 0.1,
    code: "SAT — Declaración Anual",
    note: "ISR: 10% sobre ganancias en BMV. Extranjero: tasa general ISR. Deadline: Apr 30.",
    ass: ["Acciones", "ETF", "Opciones", "Futuros", "Forex", "Cripto", "Otro"],
  },
  CL: {
    name: "Chile",
    flag: "CL",
    cur: "CLP",
    sym: "$",
    sc: "INTL",
    taxMode: "annual",
    rate: 0.1,
    code: "Formulario 22",
    note: "Impuesto ganancias de capital: 10% (Ley 21.210). F22 deadline: Apr 30.",
    ass: ["Acciones", "ETF", "Futuros", "Forex", "Cripto", "Otro"],
  },
  CO: {
    name: "Colombia",
    flag: "CO",
    cur: "COP",
    sym: "$",
    sc: "INTL",
    taxMode: "annual",
    rate: 0.15,
    code: "Declaración Renta",
    note: "Ganancia ocasional: 15% (activos < 2 años). Deadline: August (varies).",
    ass: ["Acciones", "ETF", "Futuros", "Forex", "Cripto", "Otro"],
  },
  NZ: {
    name: "New Zealand",
    flag: "NZ",
    cur: "NZD",
    sym: "NZ$",
    sc: "INTL",
    taxMode: "annual",
    rate: null,
    code: "IR3",
    note: "No general CGT. Active traders: income tax at marginal rate. FIF rules for foreign investments. IR3 deadline: Jul 7.",
    ass: ["Stocks", "ETF", "Options", "Futures", "Forex", "Crypto", "Other"],
  },
};

export const BROKERS: Record<string, string[]> = {
  BR: ["BTG Pactual", "XP Investimentos", "Clear", "Rico", "Modal", "Inter", "Ágora", "Órama", "Genial", "Outra"],
  BR_INTL: ["ZeroMarkets", "IC Markets", "Pepperstone", "XM", "FxPro", "eToro", "FTMO", "Outro"],
  US: ["Interactive Brokers", "TD Ameritrade/Schwab", "tastytrade", "E*TRADE", "Webull", "Robinhood", "Fidelity", "TradeStation", "Other"],
  GB: ["IG", "CMC Markets", "Interactive Brokers", "Spreadex", "Plus500", "eToro UK", "Hargreaves Lansdown", "Other"],
  AU: ["CommSec", "IG Australia", "CMC Markets", "Interactive Brokers AU", "Stake", "Superhero", "Other"],
  CA: ["Interactive Brokers Canada", "Questrade", "TD Direct Investing", "Wealthsimple", "Other"],
  DE: ["Interactive Brokers", "DEGIRO", "Trade Republic", "Comdirect", "Flatex", "Other"],
  FR: ["Interactive Brokers", "DEGIRO", "Bourse Direct", "Fortuneo", "Other"],
  PT: ["Interactive Brokers", "DEGIRO", "BiG", "Carregosa", "XTB", "Other"],
};

export function brokersFor(country: string): string[] {
  return BROKERS[country] ?? ["Interactive Brokers", "Local broker", "Other"];
}

export function jurisdiction(country: string | undefined | null): Jurisdiction {
  if (country && J[country]) return J[country];
  return J.US;
}
