import { readLocale, type Locale } from "@/lib/i18n";

const labels: Record<Locale, Record<string, string>> = {
  pt: {
    salary: "Salário / Pró-labore",
    extra: "Renda extra / freelance",
    investIncome: "Rendimentos de investimentos",
    otherIncome: "Outras receitas",
    housing: "Moradia (aluguel ou financiamento)",
    condo: "Condomínio",
    energy: "Energia elétrica",
    water: "Água",
    internet: "Internet / telefone",
    insurance: "Seguros",
    education: "Educação",
    subscriptions: "Assinaturas",
    food: "Alimentação / mercado",
    transport: "Transporte / combustível",
    leisure: "Lazer",
    personal: "Cuidados pessoais",
    clothing: "Vestuário",
    otherVar: "Outras despesas variáveis",
    cardPay: "Juros e encargos do cartão",
    loanPay: "Pagamento de empréstimos e financiamentos",
    cardSpend: "Compras no crédito",
  },
  en: {
    salary: "Salary / owner's draw",
    extra: "Side income / freelance",
    investIncome: "Investment income",
    otherIncome: "Other income",
    housing: "Housing (rent or mortgage)",
    condo: "HOA / condo fee",
    energy: "Electric bill",
    water: "Water",
    internet: "Internet / phone",
    insurance: "Insurance",
    education: "Education",
    subscriptions: "Subscriptions",
    food: "Groceries",
    transport: "Transport / fuel",
    leisure: "Leisure",
    personal: "Personal care",
    clothing: "Clothing",
    otherVar: "Other variable expenses",
    cardPay: "Card interest and fees",
    loanPay: "Loan and mortgage payments",
    cardSpend: "Credit card purchases",
  },
  es: {
    salary: "Sueldo / retiro del titular",
    extra: "Ingreso extra / freelance",
    investIncome: "Rendimientos de inversiones",
    otherIncome: "Otros ingresos",
    housing: "Vivienda (alquiler o hipoteca)",
    condo: "Expensas / condominio",
    energy: "Luz",
    water: "Agua",
    internet: "Internet / teléfono",
    insurance: "Seguros",
    education: "Educación",
    subscriptions: "Suscripciones",
    food: "Alimentos / supermercado",
    transport: "Transporte / combustible",
    leisure: "Ocio",
    personal: "Cuidado personal",
    clothing: "Ropa",
    otherVar: "Otros gastos variables",
    cardPay: "Intereses y cargos de la tarjeta",
    loanPay: "Pago de préstamos e hipotecas",
    cardSpend: "Compras con tarjeta",
  },
};

export function lineLabel(key: string, fallback = ""): string {
  const loc = readLocale();
  return labels[loc][key] ?? labels.pt[key] ?? fallback;
}
