/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as InstalarRouteImport } from './routes/instalar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiAsaasWebhookRouteImport } from './routes/api/asaas/webhook'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBillingWebhookRouteImport } from './routes/api/billing/webhook'
import { Route as ApiInboundEmailRouteImport } from './routes/api/inbound/email'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalarRoute = InstalarRouteImport.update({
  id: '/instalar',
  path: '/instalar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAsaasWebhookRoute = ApiAsaasWebhookRouteImport.update({
  id: '/api/asaas/webhook',
  path: '/api/asaas/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingWebhookRoute = ApiBillingWebhookRouteImport.update({
  id: '/api/billing/webhook',
  path: '/api/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInboundEmailRoute = ApiInboundEmailRouteImport.update({
  id: '/api/inbound/email',
  path: '/api/inbound/email',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conta': typeof ContaRoute
  '/instalar': typeof InstalarRoute
  '/login': typeof LoginRoute
  '/api/asaas/webhook': typeof ApiAsaasWebhookRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/inbound/email': typeof ApiInboundEmailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conta': typeof ContaRoute
  '/instalar': typeof InstalarRoute
  '/login': typeof LoginRoute
  '/api/asaas/webhook': typeof ApiAsaasWebhookRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/inbound/email': typeof ApiInboundEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conta': typeof ContaRoute
  '/instalar': typeof InstalarRoute
  '/login': typeof LoginRoute
  '/api/asaas/webhook': typeof ApiAsaasWebhookRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/inbound/email': typeof ApiInboundEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conta'
    | '/instalar'
    | '/login'
    | '/api/asaas/webhook'
    | '/api/auth/$'
    | '/api/billing/webhook'
    | '/api/inbound/email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conta'
    | '/instalar'
    | '/login'
    | '/api/asaas/webhook'
    | '/api/auth/$'
    | '/api/billing/webhook'
    | '/api/inbound/email'
  id:
    | '__root__'
    | '/'
    | '/conta'
    | '/instalar'
    | '/login'
    | '/api/asaas/webhook'
    | '/api/auth/$'
    | '/api/billing/webhook'
    | '/api/inbound/email'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContaRoute: typeof ContaRoute
  InstalarRoute: typeof InstalarRoute
  LoginRoute: typeof LoginRoute
  ApiAsaasWebhookRoute: typeof ApiAsaasWebhookRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBillingWebhookRoute: typeof ApiBillingWebhookRoute
  ApiInboundEmailRoute: typeof ApiInboundEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalar': {
      id: '/instalar'
      path: '/instalar'
      fullPath: '/instalar'
      preLoaderRoute: typeof InstalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/asaas/webhook': {
      id: '/api/asaas/webhook'
      path: '/api/asaas/webhook'
      fullPath: '/api/asaas/webhook'
      preLoaderRoute: typeof ApiAsaasWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/webhook': {
      id: '/api/billing/webhook'
      path: '/api/billing/webhook'
      fullPath: '/api/billing/webhook'
      preLoaderRoute: typeof ApiBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inbound/email': {
      id: '/api/inbound/email'
      path: '/api/inbound/email'
      fullPath: '/api/inbound/email'
      preLoaderRoute: typeof ApiInboundEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContaRoute: ContaRoute,
  InstalarRoute: InstalarRoute,
  LoginRoute: LoginRoute,
  ApiAsaasWebhookRoute: ApiAsaasWebhookRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBillingWebhookRoute: ApiBillingWebhookRoute,
  ApiInboundEmailRoute: ApiInboundEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
